### ISSUE TITLE
session_duration_seconds does not seem to have any effect

### ISSUE THREAD

**Issue by devt** [GESkunkworks/gossamer#16]
Very minor issue, but It seems the **session_duration_seconds** value specified in config has no effect.
```yaml
  primary_assumptions:
    all_roles: false
    mappings:
      - role_arn: arn:aws:iam::123123123121:role/admin
        profile_name: admin
        session_duration_seconds: 7200
```
at least for primary_assumptions.mappings I tried to set it to 2 hours, but it was still assumed for  12 hours. Granted this is a SAML federated role, so possibly the 12 hours are coming from there.

Full config is as follows:
```yaml
output_file: "~/.aws/credentials"
flows:
- name: mfa-saml-prd
  type: saml
  region: us-east-1
  do_not_propagate_region: false
  allow_failure: false

  saml_config:
    #allow_mapping_duration_override: true
    username:
      source: "env"
      value: "USERNAME"
    password:
      source: "env"
      value: "TOKEN"
    url:
      source: "config"
      value: "<MY_SSO_PROVIDER_URL>"
    target:
      source: "config"
      value: "<MY_LOGIN_URL>"

  primary_assumptions:
    all_roles: false
    mappings:
      - role_arn: arn:aws:iam::123123123121:role/admin
        profile_name: admin
        session_duration_seconds: 7200

  secondary_assumptions:
    all_roles: false
    mappings:
      - role_arn: arn:aws:iam::123123123125:role/admin
        profile_name: account1

```
